CREATE TABLE IF NOT EXISTS mpa(
                                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films(
                                    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                    name VARCHAR NOT NULL,
                                    description VARCHAR(200),
                                    release_date date,
                                    duration INTEGER,
                                    mpa_id INTEGER REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS users(
                                    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                    email VARCHAR NOT NULL,
                                    login VARCHAR NOT NULL,
                                    name VARCHAR,
                                    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS genres(
                                    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                    name VARCHAR
);

CREATE TABLE IF NOT EXISTS film_genres(
                                         film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
                                         genre_id INTEGER REFERENCES genres(id),
                                         PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes(
                                         user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                                         film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
                                         PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friendship(
                                         user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                                         friend_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                                         status VARCHAR(50),
                                         PRIMARY KEY (user_id, friend_id)
);