DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS mpa(
                                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films(
                                    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                    name VARCHAR NOT NULL,
                                    description VARCHAR(200),
                                    release_date date,
                                    duration INTEGER,
                                    mpa_id INTEGER REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS users(
                                    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                    email VARCHAR NOT NULL,
                                    login VARCHAR NOT NULL,
                                    name VARCHAR,
                                    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS genres(
                                    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                    name VARCHAR
);

CREATE TABLE IF NOT EXISTS film_genres(
                                         film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
                                         genre_id INTEGER REFERENCES genres(id),
                                         PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes(
                                         user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                                         film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
                                         PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friendship(
                                         user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                                         friend_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                                         status VARCHAR(50),
                                         PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS reviews(
                                        id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                        content TEXT NOT NULL,
                                        is_positive BOOLEAN NOT NULL,
                                        user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
                                        film_id BIGINT REFERENCES films(id) ON DELETE CASCADE NOT NULL,
                                        useful INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS review_votes(
                                           review_id BIGINT REFERENCES reviews(id) ON DELETE CASCADE NOT NULL,
                                           user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
                                           vote_type BOOLEAN NOT NULL,
                                           PRIMARY KEY(review_id, user_id)
);

CREATE TABLE IF NOT EXISTS feeds(
                                    event_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
                                    timestamp BIGINT NOT NULL,
                                    event_type VARCHAR(50) NOT NULL,
                                    operation VARCHAR(50) NOT NULL,
                                    entity_id BIGINT NOT NULL
                                    review_id BIGINT REFERENCES reviews(id) ON DELETE CASCADE NOT NULL,
                                    vote_type BOOLEAN NOT NULL,
                                    PRIMARY KEY(review_id, user_id)
);

CREATE TABLE IF NOT EXISTS directors(
                                    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS films_directors(
                                         film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
                                         director_id BIGINT REFERENCES directors(id) ON DELETE CASCADE,
                                         PRIMARY KEY (film_id, director_id)
);